version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: fcg-postgres
    restart: always
    environment:
      POSTGRES_DB: fcg_db
      POSTGRES_USER: fcg_user
      POSTGRES_PASSWORD: fcg_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: